### ISSUE TITLE
No module named 'gcnIO'

### ISSUE THREAD

**Issue by jonsenhb** [zhanglab-aim/EMGNN#1]
When I executed `python train.py --gcn 1`, I encountered the following error:
`> python train.py --gcn 1
Traceback (most recent call last):
  File "train.py", line 23, in <module>
    import gcnIO
ModuleNotFoundError: No module named 'gcnIO'`

**Comment by MichailChatzianastasis** [comment]
Thanks for letting us know. I have added the 'gcnIO.py' file to the repo. It should work now.

**Comment by jonsenhb** [comment]
thank you very much.
